### ISSUE TITLE
gpt机器人返回的信息无法按照html格式显示

### ISSUE THREAD

**Issue by xinmans** [shinyypig/gpt3-bot#1]
S L,  [2023/1/27 10:31]
给我讲个编程笑话

gpt-bot, [2023/1/27 10:32]
<p>编程笑话？好的，这是一个关于程序员和技术支持的笑话：</p>
<p>一个程序员正在尝试解决一个问题，但是他无法解决。他打电话给技术支持，问他们能否帮助他。技术支持回复道：“当然可以！你只需要重新启动电脑就行了。”</p>

 Can not parse this HTML.

是哪里设置不对吗

**Comment by shinyypig** [comment]
这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。

**Comment by xinmans** [comment]
> 这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。

可读性差了太多了，有办法转换一下？

**Comment by shinyypig** [comment]
> > 这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。
> 
> 可读性差了太多了，有办法转换一下？

不明白，什么意思？
你可以用/print输出一下对话信息，粘贴到这里看一下。
如果是不希望gpt输出html格式？那你用/set 改一下prompt head就行。

**Comment by xinmans** [comment]
> > > 这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。
> > 
> > 
> > 可读性差了太多了，有办法转换一下？
> 
> 不明白，什么意思？ 你可以用/print输出一下对话信息，粘贴到这里看一下。 如果是不希望gpt输出html格式？那你用/set 改一下prompt head就行。

![image](https://user-images.githubusercontent.com/2713008/215118176-78bdd353-47ff-4f97-a5e8-2424f2f11d99.png)
看了下code，运行/clear后可以走txt模式了，/set那部分好像有点问题，你可以再调试下

**Comment by shinyypig** [comment]
> > > > 这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。
> > > 
> > > 
> > > 可读性差了太多了，有办法转换一下？
> > 
> > 
> > 不明白，什么意思？ 你可以用/print输出一下对话信息，粘贴到这里看一下。 如果是不希望gpt输出html格式？那你用/set 改一下prompt head就行。
> 
> ![image](https://user-images.githubusercontent.com/2713008/215118176-78bdd353-47ff-4f97-a5e8-2424f2f11d99.png) 看了下code，运行/clear后可以走txt模式了，/set那部分好像有点问题，你可以再调试

> > > > 这个没关系的，因为电报机器人只支持特定的HTML标签，有的时候gpt3的输出格式不一定能用，代码里面就直接让机器人输出原文，然后加一句Can not parse this HTML.表明是直接输出的原文。
> > > 
> > > 
> > > 可读性差了太多了，有办法转换一下？
> > 
> > 
> > 不明白，什么意思？ 你可以用/print输出一下对话信息，粘贴到这里看一下。 如果是不希望gpt输出html格式？那你用/set 改一下prompt head就行。
> 
> ![image](https://user-images.githubusercontent.com/2713008/215118176-78bdd353-47ff-4f97-a5e8-2424f2f11d99.png) 看了下code，运行/clear后可以走txt模式了，/set那部分好像有点问题，你可以再调试下

你看一下readme再用吧 /set 后面跟的文字是用来定位gpt3的身份的，或者去openai看一下文档。

**Comment by xinmans** [comment]
这个/set 运行之后 返回的 changed to 就没了，changed to什么呀

**Comment by shinyypig** [comment]
你试试下面的步骤，直接在对话框里面输入:

- /clear
- /set 我是一只猫，任何问题我都只会回答喵喵喵。
- 今天天气怎么样？

「/set」后面要跟上prompt header的，也就是你对gpt3的定位。你什么都不写，当然change to后面什么都没了。

请仔细看完readme再来问问题。
